version: '3'
services:

## Router
  router01:
    image: mongo:6.0.1
    container_name: router-01
    command: mongos --port 27017 --configdb rs-config-server/configsvr01:27017,configsvr02:27017,configsvr03:27017 --bind_ip_all
    ports:
      - 27117:27017
    restart: always
    volumes:
      - ./scripts:/scripts
      - /root/fast-gpt/mongo/router01/data:/data/db
      - /root/fast-gpt/mongo/router01/config:/data/configdb
    networks:
      - custom_app_net
  router02:
    image: mongo:6.0.1
    container_name: router-02
    command: mongos --port 27017 --configdb rs-config-server/configsvr01:27017,configsvr02:27017,configsvr03:27017 --bind_ip_all
    volumes:
      - ./scripts:/scripts
      - /root/fast-gpt/mongo/router02/data:/data/db
      - /root/fast-gpt/mongo/router02/config:/data/configdb
    ports:
      - 27118:27017
    restart: always
    links:
      - router01
    networks:
      - custom_app_net

## Config Servers
  configsvr01:
    image: mongo:6.0.1
    container_name: mongo-config-01 
    command: mongod --port 27017 --configsvr --replSet rs-config-server
    volumes:
      - ./scripts:/scripts 
      - /root/fast-gpt/mongo/configsvr01/data:/data/db
      - /root/fast-gpt/mongo/configsvr01/config:/data/configdb
    ports:
      - 27119:27017
    restart: always
    links:
      - shard01-a
      - shard02-a
      - shard03-a
    networks:
      - custom_app_net
  configsvr02:
    image: mongo:6.0.1
    container_name: mongo-config-02 
    command: mongod --port 27017 --configsvr --replSet rs-config-server
    volumes:
      - ./scripts:/scripts
      - /root/fast-gpt/mongo/configsvr02/data:/data/db
      - /root/fast-gpt/mongo/configsvr02/config:/data/configdb
    ports:
      - 27120:27017
    restart: always
    links:
      - configsvr01
    networks:
      - custom_app_net
  configsvr03:
    image: mongo:6.0.1
    container_name: mongo-config-03 
    command: mongod --port 27017 --configsvr --replSet rs-config-server
    volumes:
      - ./scripts:/scripts
      - /root/fast-gpt/mongo/configsvr03/data:/data/db
      - /root/fast-gpt/mongo/configsvr03/config:/data/configdb
    ports:
      - 27121:27017
    restart: always
    links:
      - configsvr02
    networks:
      - custom_app_net

## Shards
  ## Shards 01
   
  shard01-a:
    image: mongo:6.0.1
    container_name: shard-01-node-a
    command: mongod --port 27017 --shardsvr --replSet rs-shard-01
    volumes:
      - ./scripts:/scripts
      - /root/fast-gpt/mongo/share01-a/data:/data/db
      - /root/fast-gpt/mongo/share01-a/config:/data/configdb
    ports:
      - 27122:27017
    restart: always
    links:
      - shard01-b
      - shard01-c
    networks:
      - custom_app_net
  shard01-b:
    image: mongo:6.0.1
    container_name: shard-01-node-b
    command: mongod --port 27017 --shardsvr --replSet rs-shard-01
    volumes:
      - ./scripts:/scripts
      - /root/fast-gpt/mongo/share01-b/data:/data/db
      - /root/fast-gpt/mongo/share01-b/config:/data/configdb
    ports:
      - 27123:27017
    restart: always
    networks:
      - custom_app_net
  shard01-c:
    image: mongo:6.0.1
    container_name: shard-01-node-c
    command: mongod --port 27017 --shardsvr --replSet rs-shard-01
    volumes:
      - ./scripts:/scripts
      - /root/fast-gpt/mongo/share01-c/data:/data/db
      - /root/fast-gpt/mongo/share01-c/config:/data/configdb
    ports:
      - 27124:27017
    restart: always
    networks:
      - custom_app_net

  ## Shards 02
  shard02-a:
    image: mongo:6.0.1
    container_name: shard-02-node-a
    command: mongod --port 27017 --shardsvr --replSet rs-shard-02
    volumes:
      - ./scripts:/scripts
      - /root/fast-gpt/mongo/share02-a/data:/data/db
      - /root/fast-gpt/mongo/share02-a/config:/data/configdb
    ports:
      - 27125:27017
    restart: always
    links:
      - shard02-b
      - shard02-c
    networks:
      - custom_app_net
  shard02-b:
    image: mongo:6.0.1
    container_name: shard-02-node-b
    command: mongod --port 27017 --shardsvr --replSet rs-shard-02
    volumes:
      - ./scripts:/scripts
      - /root/fast-gpt/mongo/share02-b/data:/data/db
      - /root/fast-gpt/mongo/share02-b/config:/data/configdb
    ports:
      - 27126:27017
    restart: always
    networks:
      - custom_app_net
  shard02-c:
    image: mongo:6.0.1
    container_name: shard-02-node-c
    command: mongod --port 27017 --shardsvr --replSet rs-shard-02
    volumes:
      - ./scripts:/scripts
      - /root/fast-gpt/mongo/share02-c/data:/data/db
      - /root/fast-gpt/mongo/share02-c/config:/data/configdb
    ports:
      - 27127:27017
    restart: always
    networks:
      - custom_app_net

  ## Shards 03
  shard03-a:
    image: mongo:6.0.1
    container_name: shard-03-node-a
    command: mongod --port 27017 --shardsvr --replSet rs-shard-03
    volumes:
      - ./scripts:/scripts
      - /root/fast-gpt/mongo/share03-a/data:/data/db
      - /root/fast-gpt/mongo/share03-a/config:/data/configdb
    ports:
      - 27128:27017
    restart: always
    links:
      - shard03-b
      - shard03-c
    networks:
      - custom_app_net
  shard03-b:
    image: mongo:6.0.1
    container_name: shard-03-node-b
    command: mongod --port 27017 --shardsvr --replSet rs-shard-03
    volumes:
      - ./scripts:/scripts
      - /root/fast-gpt/mongo/share03-b/data:/data/db
      - /root/fast-gpt/mongo/share03-b/config:/data/configdb
    ports:
      - 27129:27017
    restart: always
    networks:
      - custom_app_net
  shard03-c:
    image: mongo:6.0.1
    container_name: shard-03-node-c
    command: mongod --port 27017 --shardsvr --replSet rs-shard-03
    volumes:
      - ./scripts:/scripts
      - /root/fast-gpt/mongo/share03-c/data:/data/db
      - /root/fast-gpt/mongo/share03-c/config:/data/configdb
    ports:
      - 27130:27017
    restart: always
    networks:
      - custom_app_net

networks:
  custom_app_net:
    name: yanxi_net
    external: true